#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_login:
    path: /login
    controller: lexik_jwt_authentication.handler.authentication_success
    methods: ['POST']
